runtime: java21  # Specify Java 21 runtime
#env: flex
instance_class: F2  # Optional, defines the instance class (you can adjust this)
automatic_scaling:
  max_instances: 2  # Number of instances to scale up to
  min_idle_instances: 1  # Minimum number of idle instances
### Optional environment variables
env_variables:
  SPRING_PROFILES_ACTIVE: "prod"